version: '3.8'
services:
  chatbot:
    build: .
    container_name: chatbot_app
    ports:
      - "1010:1010"
    environment:
      - PORT=1010
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
