name: Revisar dependencias

on:
  workflow_dispatch:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  revisar_dependencias:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Listar todas las dependencias instaladas
        run: npm list --all

      # Si tienes un escáner de vulnerabilidades, deja el siguiente paso
      - name: Escanear vulnerabilidades con npm audit
        run: npm audit --audit-level=low --json || true

      # (Opcional) Subir el listado a los artefactos del workflow
      - name: Guardar reporte de dependencias
        run: npm list --all > reporte_dependencias.txt

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: reporte-dependencias
          path: reporte_dependencias.txt