name: Generar reporte de vulnerabilidades

on:
  workflow_dispatch:
  push:
    branches: [prueba_1]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar auditoría de seguridad
        run: npm audit --json > audit.json

      - name: Instalar dependencias Python para PDF
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install reportlab

      - name: Generar reporte PDF de vulnerabilidades
        run: |
          python3 <<EOF
          import json
          from reportlab.lib.pagesizes import letter
          from reportlab.pdfgen import canvas

          with open('audit.json', 'r') as f:
              data = json.load(f)

          c = canvas.Canvas("reporte_vulnerabilidades.pdf", pagesize=letter)
          c.setFont("Helvetica-Bold", 16)
          c.drawString(72, 750, "Reporte de Vulnerabilidades de Dependencias")
          c.setFont("Helvetica", 12)
          y = 720

          c.drawString(72, y, f"Total de vulnerabilidades: {data.get('metadata', {}).get('vulnerabilities', {})}")
          y -= 24

          advisories = data.get("advisories", {})
          if advisories:
              for advisory in advisories.values():
                  if y < 100:
                      c.showPage()
                      y = 750
                  c.setFont("Helvetica-Bold", 12)
                  c.drawString(72, y, f"{advisory['module_name']} - {advisory['severity'].capitalize()}")
                  y -= 16
                  c.setFont("Helvetica", 10)
                  c.drawString(100, y, f"ID: {advisory['id']}, {advisory['title']}")
                  y -= 14
                  c.drawString(100, y, f"URL: {advisory['url']}")
                  y -= 14
                  c.drawString(100, y, f"Recomendación: {advisory['recommendation']}")
                  y -= 20
          else:
              c.drawString(72, y, "No se encontraron vulnerabilidades.")
          c.save()
          EOF

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte_vulnerabilidades
          path: reporte_vulnerabilidades.pdf